name: Docker Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install OpenVPN
        run: |
          sudo apt-get update
          sudo apt-get --assume-yes --no-install-recommends install openvpn          
      
      - name: Setup VPN config
        run: |
          echo "${{ secrets.AWS_CLIENT_VPN_CONFIG }}" > config.ovpn  

      - name: Connect VPN
        run: sudo openvpn --config "config.ovpn"

      - name: Docker Build
        run: docker build . -t payment-gateway:${{ github.run_id }}
