name: Docker Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install OpenVPN
        run: |
          sudo apt-get update
          sudo apt-get --assume-yes --no-install-recommends install openvpn          
      
      - name: Setup VPN config
        run: |
          echo "${{ secrets.AWS_CLIENT_VPN_CONFIG }}" > config.ovpn  

      - name: Connect VPN
        run: sudo openvpn --config "config.ovpn" --daemon
        
      - name: Wait for a VPN connection
        timeout-minutes: 1
        run: until ping -c1 10.0.1.104; do sleep 2; done
        
      - name: Connect buildx
        run: docker buildx ls
        
      - name: Setup
        run: docker buildx create --name remote-buildkit-host --driver remote tcp://10.0.1.104:8082


      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          builder: remote-buildkit-host
          tags: test:pr-42

      - name: Kill VPN connection
        if: always()
        run: |
          sudo killall openvpn    

