name: Docker Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  REGISTRY: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to GHCR
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: app
      
      - name: Build and push
        uses: docker/build-push-action@v3.3.0
        with:
          context: .
          push: true
          file: ./Dockerfile
          builder: remote-buildkit-host
          tags: ghcr.io/karimdarwish/${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
