name: Docker Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  REGISTRY: ghcr.io/karimdarwish/payment-gateway

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to GHCR
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: app
          
      - name: Push
        run: docker buildx build --push -t ${{ env.REGISTRY }}/${{ steps.meta.outputs.tags }} .

      - name: Logs
        if: always()
        run: docker logs buildx_buildkit_remote-buildkit-host
