name: Docker Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  REGISTRY: ghcr.io/karimdarwish/payment-gateway

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      
      - name: Docker Login
        run: sudo docker login ghcr.io/karimdarwish/payment-gateway -u KarimDarwish -p ${{ secrets.GCR_PAT }}
          
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: app
          
      - name: Push
        run: sudo docker buildx build --push -t ghcr.io/karimdarwish/payment-gateway/app:pr-39 .

      - name: Logs
        if: always()
        run: docker logs buildx_buildkit_remote-buildkit-host
