name: Docker Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  REGISTRY: ghcr.io/karimdarwish/payment-gateway

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v2
      
      - name: Docker Login
        run: sudo docker login ${{ env.REGISTRY }} -u ${{ github.repository_owner }} -p ${{ secrets.GCR_PAT }}
          
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: app
          
      - name: Push
        run: sudo docker buildx build --push -t ${{ env.REGISTRY }}/${{ steps.meta.outputs.tags }} .

      - name: Logs
        if: always()
        run: docker logs buildx_buildkit_remote-buildkit-host
