name: Docker Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      
      - name: Docker Build
        run: docker buildx build --tag payment-gateway:${{ github.run_id }} --cache-from type=local,dest=./mnt/efs/fs1/docker --import-cache type=local,src=./mnt/efs/fs1/docker .
