name: Docker Build
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Docker Build
        run: docker build . -t payment-gateway:${{ github.run_id }}
