name: Docker Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - uses: KarimDarwish/remote-buikdkit-action@v0.0.2-alpha
        with:
          openvpn-config: ${{ secrets.BUILDKIT_OPENVPN_CONFIG }}
          buildkit-ca-cert: ${{ secrets.BUILDKIT_CLIENT_CA_CERT }}
          buildkit-cert: ${{ secrets.BUILDKIT_CLIENT_CERT }}
          buildkit-cert-key: ${{ secrets.BUILDKIT_CLIENT_KEY }}
          buildkit-ip: ${{ secrets.BUILDKIT_HOST_IP }}

      - name: Connect buildx
        run: docker buildx ls

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          builder: remote-buildkit-host
          tags: test:pr-42

      - name: Kill VPN connection
        if: always()
        run: |
          sudo killall openvpn    

