name: Docker Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  REGISTRY: ghcr.io/karimdarwish/payment-gateway

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Buildx 1
        if: always()
        run: docker buildx ls

      - name: Use Buildx 1
        if: always()
        run: docker buildx rm remote-buildkit-host-1
        
  #    - name: Docker Login
  #      if: always()
  #      run: sudo docker login ghcr.io/karimdarwish/payment-gateway -u KarimDarwish -p ${{ secrets.GCR_PAT }}
                    
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io/karimdarwish/payment-gateway
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          builder: remote-buildkit-host
          tags: ghcr.io/karimdarwish/payment-gateway/app:pr-39
#      - name: Push
#        if: always()
 #       run: sudo docker buildx build --push -t ghcr.io/karimdarwish/payment-gateway/app:pr-39 .
