name: Docker Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  REGISTRY: ghcr.io/karimdarwish/payment-gateway

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Buildx 1
        if: always()
        run: docker buildx ls
                    
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: 906437365765.dkr.ecr.eu-central-1.amazonaws.com/test
          username: ${{ secrets.ECR_ACCESS_KEY }}
          password: ${{ secrets.ECR_SECRET }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          builder: remote-buildkit-host
          tags: 906437365765.dkr.ecr.eu-central-1.amazonaws.com/test:pr-40
